// 7. Heat Generation in Machines
// Input: Two floating-point numbers: power usage (Watts) and efficiency (%).
// Output: Heat generated (Joules).
// Function:
// float calculate_heat(float power_usage, float efficiency);




#include <stdio.h>

float calculate_heat(float power_usage, float efficiency);


int main() {

    float power_usage, efficiency, heat_generated;

    
    printf("Enter the power usage of the machine (in Watts): ");
    scanf("%f", &power_usage);

    
    printf("Enter the efficiency of the machine (in %%): ");
    scanf("%f", &efficiency);

    
    heat_generated = calculate_heat(power_usage, efficiency);

    if (heat_generated != -1) {
        printf("The heat generated by the machine is: %.2f Joules\n", heat_generated);
    }

    return 0;
}


float calculate_heat(float power_usage, float efficiency) {

    if (power_usage < 0 || efficiency < 0 || efficiency > 100) {
        printf("Invalid input. Power usage must be non-negative, and efficiency must be between 0 and 100.\n");
        return -1; 
    }
    return power_usage * (1 - (efficiency / 100));
}